[package]
name = "csv_file"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv="1.1"
serde="1"
serde_derive="1.0.132"
rocket="0.5.0-rc.1"
